name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: flake8
        run: |
          flake8 .
      - uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
          jupyter: true
      - name: isort
        run: |
          isort --check-only --diff --verbose --profile black .
